config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resource :users, only:[:new, :create]
  get '/room', to: 'rooms#show'
  get 'auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/messages', to: 'rooms#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  mount_uploader :picture, PictureUploader
  # after_create_commit { MessageBroadcastJob.perform_later self }
  validates :content, presence: true
  validate :picture_size

  private

    def picture_size
      if picture.size > 5.megabytes
        errors.add :picture, 'should be less than 5MB'
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages, dependent: :destroy
  validates :name, presence: true, uniqueness: true

  mount_uploader :image, ImageUploader

  def self.find_or_create_from_auth(auth)
    provider = auth[:provider]
    uid = auth[:uid]
    nickname = auth[:info][:nickname]

    self.find_or_create_by(provider: provider, uid: uid) do |user|
      user.nickname = nickname
      # user.image_url = image_url
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    if entered?
      @message = Message.new
      @messages = Message.all
    else
      flash[:danger] = 'Please create user'
      redirect_to root_path
    end
  end

  def create
    @message = current_user.messages.build(params_message)
    if @message.save
      RoomChannel.broadcast_to 'room_channel', message: render_message(@message)
    else
      puts 'message_errors'
      puts @message.errors.full_messages
    end
  end

  def create_twitter

  end

  private
    def params_message
      params.require(:message).permit(:content, :picture)
    end

    def render_message(message)
      ApplicationController.renderer.render(partial: 'messages/message',
                      locals: { message: message })
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    current_user.uid = request.env['omniauth.auth'][:uid]
    current_user.nickname = request.env['omniauth.auth'][:info][:nickname]
    current_user.save
    enter current_user
    redirect_to room_path
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      enter @user
      redirect_to room_url
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def get_profile_image(message)
    get_twitter_data(message)[0]
  end

  def get_profile_name(message)
    get_twitter_data(message)[1]
  end

  def get_profile_nick_name(message)
    get_twitter_data(message)[2]
  end

  def get_profile_description(message)
    get_twitter_data(message)[3]
  end

  def get_profile_url(message)
    get_twitter_data(message)[4]
  end

  def get_twitter_data(message)
    data = []
    message.lines { |line| data.push line }
    data
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def enter(user)
    session[:user_id] = user.id
    session[:u_id] = user.uid unless user.uid.nil?
  end

  def entered?
    !session[:user_id].nil?
  end

  def leave
    session.delete :user_id
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by(id: user_id)
    end
  end

  def logged_in?
    !!session[:user_id]
  end

  def logged_in_with_twitter?
    !!session[:u_id]
  end

  def authenticate
    return if logged_in?
    redirect_to root_path, alert: 'ログインしてください'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | SampleChat
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body data-action=("#{action_name}") data-controller=("#{controller_name}")
    .flash_container
      - flash.each do |message_type, message|
        = content_tag :div, message, class: "alert alert-#{message_type}"
    = yield

app/views/messages/_message.html.slim
li.list-group-item
  .media
    .media-left
      a href='#'
        - if message.user.image?
          = image_tag message.user.image.url, size: '50x50'
        - else
          = image_tag 'no_img.png', size: '50x50'
    .media-body
      h4.media-heading
        = message.user.name
      - if message.twitter
        = render 'messages/twitter_account', { content: message.content }
      - else
        = message.content
        br
        = image_tag message.picture if message.picture?

app/views/messages/_twitter_account.html.slim
.item_header
  = link_to '', get_profile_url(content)
  span.item_user-icon
    = image_tag get_profile_image(content)
  span.item_user-name
    strong
      = get_profile_name(content)
  span.item_user-name
    = get_profile_nick_name(content)
  span.item_user-name
    = get_profile_description(content)

app/views/rooms/create.html.slim
h1 CREATE

app/views/rooms/show.html.slim
.middle.item
  h1 Chat room

  .panel.panel-default
    ul.list-group.item#messages
      = render @messages

  .btn.btn-warning.logout
    = link_to 'Leave the room', logout_path

footer.footer#chat_frame
  .container
    .row#chat_row
      .col-md-1.col-md-offset-2
        button.btn.btn-default#image_button data-placement='left'
          span.glyphicon.glyphicon-plus
      = form_for @message, html: { multipart: true, remote: true }, authenticity_token: true do |f|
        = f.file_field :picture, accept: 'image/jpeg,image/gif,image/png'
        .col-md-5
          = f.text_area :content, class: 'form-control'
        .col-md-1#send_message
          = f.submit 'Send', class: 'btn btn-primary', id: 'send_button'
      .col-md-3
        - if logged_in_with_twitter?
          a.btn.btn-block.btn-social.btn-twitter#send_twitter
            span.fa.fa-twitter
            | Send Twitter Account
        - else
          a.btn.btn-block.btn-social.btn-twitter href='auth/twitter'
            span.fa.fa-twitter
            | Login with Twitter

app/views/shared/_error_messages.html.slim
- object.errors.any?
  #error_explanation
    .alert.alert-danger
      | The form contains
      = pluralize object.errors.count, 'error'
    ul
      - object.errors.full_messages.each do |msg|
        li
          = msg

app/views/users/create.html.slim
h1 Users#create
p Find me in app/views/users/create.html.slim

app/views/users/new.html.slim
h1.text-center
  | Welcome to Sample Chat
button.btn.btn-default.btn-lg.center-block#user_img
  span.glyphicon.glyphicon-camera#camera

= form_for @user, html: { class: 'center-block', multipart: true } do |f|
  = render 'shared/error_messages', object: f.object
  = f.file_field :image
  = f.label :name, 'What is your name?', class: 'text-center center-block', id: 'user_label'
  = f.text_field :name, class: 'form-control center-block', id: 'user_name'
  = f.submit 'Enter the room', class: 'btn btn-primary center-block', id: 'new_user'